version: '3.4'

services:

  reverseproxy:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    depends_on:
      - bethanysshop
    ports:
      - "5200:5100"

  bethanysshop:
    image: ${DOCKER_REGISTRY-}bethanysshop
    build:
      context: .
      dockerfile: BethanysShop/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"

  piedb:
    build:
      context: .
      dockerfile: sql/sql.Dockerfile
    restart: always
    ports:
      - "1440:1443"
    environment:
      - SA_PASSWORD=Sqlc0ntainersFTW!
      - ACCEPT_EULA="Y"